### ISSUE TITLE
Create client-side layout

### ISSUE THREAD

**Issue by recursion** [ArmorAndMint/ArmorAndMint#11]
I think we should start mocking something up client side immediately. It does not need to send or retrieve data from the server yet. Any input/feedback on this is welcome and invited.

**Comment by Asxen** [comment]
Should include the following:
  * navbar (placeholder logo on left, placeholder signin on right)
  * hero-area (the ~50% of the top of the pages where the title/image goes)
  * a dummy article (title, body-snippet, author/date footer)
