### ISSUE TITLE
Add behavior to edit hero bio information

### ISSUE THREAD

**Issue by brukh** [ArmorAndMint/ArmorAndMint#35]

**Comment by recursion** [comment]
This should be a property on the user model.

**Comment by recursion** [comment]
This will require having a property added to the user model (imo) and then wiring up throughout the application - there are some notes in the  code already at areas where this will hook into

**Comment by Asxen** [comment]
Oh, awesome. I was trying to figure this out and was just having issues getting it to propogate to the view; then again, I'm not quite the Angular wizard here lol.

**Comment by recursion** [comment]
Awesome. - Please let me know if I can help shine a light on anything in there. I know there are some dark, cavernous areas in that code base.....lol
