### ISSUE TITLE
Decide on and layout a project skeleton.

### ISSUE THREAD

**Issue by recursion** [ArmorAndMint/ArmorAndMint#4]
We need a project skeleton to start building from.  
Gulp or Grunt?
Start with a generator or existing project stack like mean.io or meanjs.org?
How do I use this thing?
This is mostly just a test issue?

**Comment by recursion** [comment]
I think both mean.io and meanjs.org have what could be useful sort of templates for our directory structures. It would be useful to use a system which allows us to easily 'drop' in modules later. At the very least it would be useful to study these and get an idea for what we are going to be dealing with once the project grows in size.

**Comment by brukh** [comment]
I'm going to add this back to the log  -  until we decide together tomorrow.

**Comment by recursion** [comment]
Basic skeleton has been implemented and merged.
