### ISSUE TITLE
serve posts by url

### ISSUE THREAD

**Issue by Asxen** [ArmorAndMint/ArmorAndMint#42]
Set up a route such that users can go to blog.com/verbose-url-here and be taken to a specific blog post

**Comment by recursion** [comment]
Yes this is an important one.

 Ive started tinkering with this some, and there is some code in the master branch that attempts to do this, but it is not working yet. The way I see it there are a few ways we can do this: 
- The simple way: Have a route listener for something like '/blog/your-article-title-with-hyphens' which strips the hyphens, searches the db for an article with that title, and then renders a view with this article loaded. (the question becomes how/when do they switch into the native app? - I guess when/if they decide to reload/see more articles - we can load the entire index.html - giving them the full client app.
- More complex would be to find the article, then render our index.ejs (full client) WITH the article data, and a flag that tells angular which view to start in, and which article to load in that view.

**Comment by Asxen** [comment]
Another alternative would be to have database entries include a url key whose value is the associated url, which would default to the title minus punctuation replacing spaces with hyphens (i.e. title: "Hello World!", url: 'Hello-World'). The only drawback is the additional data load, but that's marginal at best.
