### ISSUE TITLE
Setup Hosting

### ISSUE THREAD

**Issue by recursion** [ArmorAndMint/ArmorAndMint#5]
Someone needs to take ownership of hosting. This person will be in charge of setting up at least 1 side of the github webhooks/automatic deployment stuff. Basically your job will be to setup the production server (cloud service or vps is fine) (and database?) and make sure that it always has the latest version of our master branch (which should be easily automated).

**Comment by recursion** [comment]
If either of you have an interest in taking this on, please step up.... otherwise Ill assume it?

**Comment by Asxen** [comment]
I could use the experience with Heroku

**Comment by recursion** [comment]
Sounds good man. You now have the helm on hosting admin  :)
