### ISSUE TITLE
Make header buttons smaller?

### ISSUE THREAD

**Issue by recursion** [ArmorAndMint/ArmorAndMint#64]

**Comment by recursion** [comment]
login/logout/new post buttons seem a bit large? 
this is totally cosmetic, and if you guys like them as is, im fine with them.. but I thought maybe there could be less somehow.

**Comment by Asxen** [comment]
I think they're okay for now. I'd be willing to see what other teams do with them, if anything. But yeah, even if we did size down the buttons it'd likely be a matter of like... 3-5px top/bottom
